### ISSUE TITLE
Factorio 2.0 Has 16 Cardinal Directions

### ISSUE THREAD

**Issue by mrgrim** [d4rkc0d3r/FactorioPumpjackBlueprint#10]
This is up from the 8 directions in 1.1. It's probably related to the new rail systems, but the result is underground pipes are facing the wrong way in blueprints generated by this tool. The table should be altered as follows:

```
    static class Direction
    {
        public const int North = 0;
        public const int East = 4;
        public const int South = 8;
        public const int West = 12;
    }

```

**Comment by d4rkc0d3r** [comment]
I added support for factorio 2.0 blueprints with [version 2.0](https://github.com/d4rkc0d3r/FactorioPumpjackBlueprint/releases/tag/v2.0)
