### ISSUE TITLE
Exception on my blueprint

### ISSUE THREAD

**Issue by Yxang** [d4rkc0d3r/FactorioPumpjackBlueprint#3]
The program crashed dealing with my blueprint. After checking I found removing arbitrary 1 of the circled 4 pumpjacks could let the program run.

![pumpjack](https://user-images.githubusercontent.com/37404326/54738129-e1415b80-4bed-11e9-8003-172b154e1130.png)

Traceback:
Unhandled Exception:  System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
  at FactorioPumpjackBlueprint.Program.LayPipes(Blueprint bp, Boolean useSpeed3, Int32 minPumpjacksPerBeacon)
   at FactorioPumpjackBlueprint.Program.Main(String[] args)

Blueprint: 
0eNqVmN1q4zAQRt9F1y5YGv3YfpWlLGlrincbJyTOsiHk3deOx2WhX8Wnq5ISn8iaMzMa3czLx6U/noZxMt3NDK+H8Wy6HzdzHt7H3cfyv+l67E1nhqnfm8qMu/3y6XjZH3/tXn+be2WG8a3/azp7f65MP07DNPQr4/Hh+nO87F/60/yFr09X5ng4zw8cxuWXZsiT9ZW5zn+9u9+rLwhHIBoF1Agg1BrcipAGITyB+CS0iBCoReh7iEeISCGSIuBWJAah0RCLCA1BUICDW9kSABeUALfS1gxCo+EiRHBetsoIkOEoRlQGDKnl3JTsOhg5U5bAyLnsegbBybkxYKJbys7PwEI9bUOtI2QZjKKbGjDNHGVom1uE4wy1K8PCRHGUoU7dsDBTHGPoJvk3CEZQkSyCKp+y7QbeUUZR0QpscVw5Q9VyHJOmQA1YQB2j55MGNcGGyOip8YDhEMuXHAygzBRNdVhxhCqdWyfBCF8SToxgxNwyDLYAiUUtACIoLUXbMkwOaQpOBpjAaKn1CiaXr6m3WAMK98FTNXPNLfgOntHS2QxAeB3wK1C1MmVWQAn5eB7q6BkdtX8KBDAyOsmsgFLRrYUan9Zb3gNYIEPNZwMGWP5EBV8hOF4kvAIpmBbwxOILkgFmdGBclJgjRP7ogLt+SAU1AQoduCNljsD4KHWGEOuCncTDoy1oMxb2uugKgoEJXM9WBPQ6+oIbBQtzKwb69PINgKqRbe4tUsH8iWeMSB0kVQmY4LGlZ3k8sCWuY69i4wE4lWjpYG4k7iy59gt8HZCEL3V4/k3cUVJ3E1qVSmYcfDOSYkHrxPc7qWTEwZdlqSkYXZc7v+dqvWns/ruYrMyf/nR+fD9JbYNvXaznn/sHxMe6gg==

**Comment by d4rkc0d3r** [comment]
This was caused by the 4 pumpjacks blocking off the inner part. It now won't crash anymore but can still result in not fully connected pipe systems. I discourage those by multiplying the optimization target by 0.5 if it cant connect all pumpjacks.
